//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NAV_HR_WINDOW.ProbationConfirmationCard_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConfirmationCard_Binding", Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public partial class ConfirmationCard_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_HR_Confirmation_KPI_AOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_HR_KPI_Confirmation_BOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_HR_Confirmation_KPI_COperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_HR_Confirmation_KPI_DOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConfirmationCard_Service() {
            this.Url = global::NAV_HR_WINDOW.Properties.Settings.Default.NAV_HR_WINDOW_ProbationConfirmationCard_Service_ConfirmationCard_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event Delete_HR_Confirmation_KPI_ACompletedEventHandler Delete_HR_Confirmation_KPI_ACompleted;
        
        /// <remarks/>
        public event Delete_HR_KPI_Confirmation_BCompletedEventHandler Delete_HR_KPI_Confirmation_BCompleted;
        
        /// <remarks/>
        public event Delete_HR_Confirmation_KPI_CCompletedEventHandler Delete_HR_Confirmation_KPI_CCompleted;
        
        /// <remarks/>
        public event Delete_HR_Confirmation_KPI_DCompletedEventHandler Delete_HR_Confirmation_KPI_DCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConfirmationCard")]
        public ConfirmationCard Read(string Application_No) {
            object[] results = this.Invoke("Read", new object[] {
                        Application_No});
            return ((ConfirmationCard)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string Application_No) {
            this.ReadAsync(Application_No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string Application_No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Application_No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConfirmationCard")]
        public ConfirmationCard ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((ConfirmationCard)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ConfirmationCard[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] ConfirmationCard_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((ConfirmationCard[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ConfirmationCard_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ConfirmationCard_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref ConfirmationCard ConfirmationCard) {
            object[] results = this.Invoke("Create", new object[] {
                        ConfirmationCard});
            ConfirmationCard = ((ConfirmationCard)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(ConfirmationCard ConfirmationCard) {
            this.CreateAsync(ConfirmationCard, null);
        }
        
        /// <remarks/>
        public void CreateAsync(ConfirmationCard ConfirmationCard, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        ConfirmationCard}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ConfirmationCard[] ConfirmationCard_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        ConfirmationCard_List});
            ConfirmationCard_List = ((ConfirmationCard[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(ConfirmationCard[] ConfirmationCard_List) {
            this.CreateMultipleAsync(ConfirmationCard_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(ConfirmationCard[] ConfirmationCard_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        ConfirmationCard_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref ConfirmationCard ConfirmationCard) {
            object[] results = this.Invoke("Update", new object[] {
                        ConfirmationCard});
            ConfirmationCard = ((ConfirmationCard)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(ConfirmationCard ConfirmationCard) {
            this.UpdateAsync(ConfirmationCard, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(ConfirmationCard ConfirmationCard, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        ConfirmationCard}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ConfirmationCard[] ConfirmationCard_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        ConfirmationCard_List});
            ConfirmationCard_List = ((ConfirmationCard[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(ConfirmationCard[] ConfirmationCard_List) {
            this.UpdateMultipleAsync(ConfirmationCard_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(ConfirmationCard[] ConfirmationCard_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        ConfirmationCard_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:Delete_HR_Confirmation_KPI_A" +
            "", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="Delete_HR_Confirmation_KPI_A_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_HR_Confirmation_KPI_A_Result")]
        public bool Delete_HR_Confirmation_KPI_A(string HR_Confirmation_KPI_A_Key) {
            object[] results = this.Invoke("Delete_HR_Confirmation_KPI_A", new object[] {
                        HR_Confirmation_KPI_A_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_HR_Confirmation_KPI_AAsync(string HR_Confirmation_KPI_A_Key) {
            this.Delete_HR_Confirmation_KPI_AAsync(HR_Confirmation_KPI_A_Key, null);
        }
        
        /// <remarks/>
        public void Delete_HR_Confirmation_KPI_AAsync(string HR_Confirmation_KPI_A_Key, object userState) {
            if ((this.Delete_HR_Confirmation_KPI_AOperationCompleted == null)) {
                this.Delete_HR_Confirmation_KPI_AOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_HR_Confirmation_KPI_AOperationCompleted);
            }
            this.InvokeAsync("Delete_HR_Confirmation_KPI_A", new object[] {
                        HR_Confirmation_KPI_A_Key}, this.Delete_HR_Confirmation_KPI_AOperationCompleted, userState);
        }
        
        private void OnDelete_HR_Confirmation_KPI_AOperationCompleted(object arg) {
            if ((this.Delete_HR_Confirmation_KPI_ACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_HR_Confirmation_KPI_ACompleted(this, new Delete_HR_Confirmation_KPI_ACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:Delete_HR_KPI_Confirmation_B" +
            "", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="Delete_HR_KPI_Confirmation_B_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_HR_KPI_Confirmation_B_Result")]
        public bool Delete_HR_KPI_Confirmation_B(string HR_KPI_Confirmation_B_Key) {
            object[] results = this.Invoke("Delete_HR_KPI_Confirmation_B", new object[] {
                        HR_KPI_Confirmation_B_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_HR_KPI_Confirmation_BAsync(string HR_KPI_Confirmation_B_Key) {
            this.Delete_HR_KPI_Confirmation_BAsync(HR_KPI_Confirmation_B_Key, null);
        }
        
        /// <remarks/>
        public void Delete_HR_KPI_Confirmation_BAsync(string HR_KPI_Confirmation_B_Key, object userState) {
            if ((this.Delete_HR_KPI_Confirmation_BOperationCompleted == null)) {
                this.Delete_HR_KPI_Confirmation_BOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_HR_KPI_Confirmation_BOperationCompleted);
            }
            this.InvokeAsync("Delete_HR_KPI_Confirmation_B", new object[] {
                        HR_KPI_Confirmation_B_Key}, this.Delete_HR_KPI_Confirmation_BOperationCompleted, userState);
        }
        
        private void OnDelete_HR_KPI_Confirmation_BOperationCompleted(object arg) {
            if ((this.Delete_HR_KPI_Confirmation_BCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_HR_KPI_Confirmation_BCompleted(this, new Delete_HR_KPI_Confirmation_BCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:Delete_HR_Confirmation_KPI_C" +
            "", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="Delete_HR_Confirmation_KPI_C_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_HR_Confirmation_KPI_C_Result")]
        public bool Delete_HR_Confirmation_KPI_C(string HR_Confirmation_KPI_C_Key) {
            object[] results = this.Invoke("Delete_HR_Confirmation_KPI_C", new object[] {
                        HR_Confirmation_KPI_C_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_HR_Confirmation_KPI_CAsync(string HR_Confirmation_KPI_C_Key) {
            this.Delete_HR_Confirmation_KPI_CAsync(HR_Confirmation_KPI_C_Key, null);
        }
        
        /// <remarks/>
        public void Delete_HR_Confirmation_KPI_CAsync(string HR_Confirmation_KPI_C_Key, object userState) {
            if ((this.Delete_HR_Confirmation_KPI_COperationCompleted == null)) {
                this.Delete_HR_Confirmation_KPI_COperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_HR_Confirmation_KPI_COperationCompleted);
            }
            this.InvokeAsync("Delete_HR_Confirmation_KPI_C", new object[] {
                        HR_Confirmation_KPI_C_Key}, this.Delete_HR_Confirmation_KPI_COperationCompleted, userState);
        }
        
        private void OnDelete_HR_Confirmation_KPI_COperationCompleted(object arg) {
            if ((this.Delete_HR_Confirmation_KPI_CCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_HR_Confirmation_KPI_CCompleted(this, new Delete_HR_Confirmation_KPI_CCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/confirmationcard:Delete_HR_Confirmation_KPI_D" +
            "", RequestNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", ResponseElementName="Delete_HR_Confirmation_KPI_D_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/confirmationcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_HR_Confirmation_KPI_D_Result")]
        public bool Delete_HR_Confirmation_KPI_D(string HR_Confirmation_KPI_D_Key) {
            object[] results = this.Invoke("Delete_HR_Confirmation_KPI_D", new object[] {
                        HR_Confirmation_KPI_D_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_HR_Confirmation_KPI_DAsync(string HR_Confirmation_KPI_D_Key) {
            this.Delete_HR_Confirmation_KPI_DAsync(HR_Confirmation_KPI_D_Key, null);
        }
        
        /// <remarks/>
        public void Delete_HR_Confirmation_KPI_DAsync(string HR_Confirmation_KPI_D_Key, object userState) {
            if ((this.Delete_HR_Confirmation_KPI_DOperationCompleted == null)) {
                this.Delete_HR_Confirmation_KPI_DOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_HR_Confirmation_KPI_DOperationCompleted);
            }
            this.InvokeAsync("Delete_HR_Confirmation_KPI_D", new object[] {
                        HR_Confirmation_KPI_D_Key}, this.Delete_HR_Confirmation_KPI_DOperationCompleted, userState);
        }
        
        private void OnDelete_HR_Confirmation_KPI_DOperationCompleted(object arg) {
            if ((this.Delete_HR_Confirmation_KPI_DCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_HR_Confirmation_KPI_DCompleted(this, new Delete_HR_Confirmation_KPI_DCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public partial class ConfirmationCard {
        
        private string keyField;
        
        private string application_NoField;
        
        private string employee_NoField;
        
        private string employee_NameField;
        
        private System.DateTime date_of_EmploymentField;
        
        private bool date_of_EmploymentFieldSpecified;
        
        private string departmentField;
        
        private string supervisorField;
        
        private string second_Line_SupervisorField;
        
        private string levelField;
        
        private Appraisal_Type appraisal_TypeField;
        
        private bool appraisal_TypeFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private System.DateTime date_of_ReviewField;
        
        private bool date_of_ReviewFieldSpecified;
        
        private System.DateTime start_DateField;
        
        private bool start_DateFieldSpecified;
        
        private System.DateTime end_DateField;
        
        private bool end_DateFieldSpecified;
        
        private decimal scoreField;
        
        private bool scoreFieldSpecified;
        
        private decimal kPI_ScoreField;
        
        private bool kPI_ScoreFieldSpecified;
        
        private string user_IDField;
        
        private string commentField;
        
        private string second_Line_Supervisor_CommentField;
        
        private string development_AreasField;
        
        private string training_IdeasField;
        
        private string employee_CommentField;
        
        private string responsibility_CenterField;
        
        private HR_Confirmation_Lines[] hR_Confirmation_LinesField;
        
        private HR_Confirmation_KPI_A[] hR_Confirmation_KPI_AField;
        
        private HR_KPI_Confirmation_B[] hR_KPI_Confirmation_BField;
        
        private HR_Confirmation_KPI_C[] hR_Confirmation_KPI_CField;
        
        private HR_Confirmation_KPI_D[] hR_Confirmation_KPI_DField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Application_No {
            get {
                return this.application_NoField;
            }
            set {
                this.application_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Employee_No {
            get {
                return this.employee_NoField;
            }
            set {
                this.employee_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Employee_Name {
            get {
                return this.employee_NameField;
            }
            set {
                this.employee_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date_of_Employment {
            get {
                return this.date_of_EmploymentField;
            }
            set {
                this.date_of_EmploymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_of_EmploymentSpecified {
            get {
                return this.date_of_EmploymentFieldSpecified;
            }
            set {
                this.date_of_EmploymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string Supervisor {
            get {
                return this.supervisorField;
            }
            set {
                this.supervisorField = value;
            }
        }
        
        /// <remarks/>
        public string Second_Line_Supervisor {
            get {
                return this.second_Line_SupervisorField;
            }
            set {
                this.second_Line_SupervisorField = value;
            }
        }
        
        /// <remarks/>
        public string Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public Appraisal_Type Appraisal_Type {
            get {
                return this.appraisal_TypeField;
            }
            set {
                this.appraisal_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Appraisal_TypeSpecified {
            get {
                return this.appraisal_TypeFieldSpecified;
            }
            set {
                this.appraisal_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date_of_Review {
            get {
                return this.date_of_ReviewField;
            }
            set {
                this.date_of_ReviewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_of_ReviewSpecified {
            get {
                return this.date_of_ReviewFieldSpecified;
            }
            set {
                this.date_of_ReviewFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Start_Date {
            get {
                return this.start_DateField;
            }
            set {
                this.start_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Start_DateSpecified {
            get {
                return this.start_DateFieldSpecified;
            }
            set {
                this.start_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime End_Date {
            get {
                return this.end_DateField;
            }
            set {
                this.end_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool End_DateSpecified {
            get {
                return this.end_DateFieldSpecified;
            }
            set {
                this.end_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal KPI_Score {
            get {
                return this.kPI_ScoreField;
            }
            set {
                this.kPI_ScoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KPI_ScoreSpecified {
            get {
                return this.kPI_ScoreFieldSpecified;
            }
            set {
                this.kPI_ScoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string User_ID {
            get {
                return this.user_IDField;
            }
            set {
                this.user_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string Second_Line_Supervisor_Comment {
            get {
                return this.second_Line_Supervisor_CommentField;
            }
            set {
                this.second_Line_Supervisor_CommentField = value;
            }
        }
        
        /// <remarks/>
        public string Development_Areas {
            get {
                return this.development_AreasField;
            }
            set {
                this.development_AreasField = value;
            }
        }
        
        /// <remarks/>
        public string Training_Ideas {
            get {
                return this.training_IdeasField;
            }
            set {
                this.training_IdeasField = value;
            }
        }
        
        /// <remarks/>
        public string Employee_Comment {
            get {
                return this.employee_CommentField;
            }
            set {
                this.employee_CommentField = value;
            }
        }
        
        /// <remarks/>
        public string Responsibility_Center {
            get {
                return this.responsibility_CenterField;
            }
            set {
                this.responsibility_CenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HR_Confirmation_Lines[] HR_Confirmation_Lines {
            get {
                return this.hR_Confirmation_LinesField;
            }
            set {
                this.hR_Confirmation_LinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HR_Confirmation_KPI_A[] HR_Confirmation_KPI_A {
            get {
                return this.hR_Confirmation_KPI_AField;
            }
            set {
                this.hR_Confirmation_KPI_AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HR_KPI_Confirmation_B[] HR_KPI_Confirmation_B {
            get {
                return this.hR_KPI_Confirmation_BField;
            }
            set {
                this.hR_KPI_Confirmation_BField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HR_Confirmation_KPI_C[] HR_Confirmation_KPI_C {
            get {
                return this.hR_Confirmation_KPI_CField;
            }
            set {
                this.hR_Confirmation_KPI_CField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HR_Confirmation_KPI_D[] HR_Confirmation_KPI_D {
            get {
                return this.hR_Confirmation_KPI_DField;
            }
            set {
                this.hR_Confirmation_KPI_DField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public enum Appraisal_Type {
        
        /// <remarks/>
        _Confirmation,
        
        /// <remarks/>
        Probation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public enum Status {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Pending_Approval,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        HR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public partial class HR_Confirmation_Lines {
        
        private string keyField;
        
        private int entry_NoField;
        
        private bool entry_NoFieldSpecified;
        
        private string responbilitiesField;
        
        private decimal available_RatingField;
        
        private bool available_RatingFieldSpecified;
        
        private decimal supervisor_RatingField;
        
        private bool supervisor_RatingFieldSpecified;
        
        private decimal employee_RatingField;
        
        private bool employee_RatingFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public int Entry_No {
            get {
                return this.entry_NoField;
            }
            set {
                this.entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entry_NoSpecified {
            get {
                return this.entry_NoFieldSpecified;
            }
            set {
                this.entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Responbilities {
            get {
                return this.responbilitiesField;
            }
            set {
                this.responbilitiesField = value;
            }
        }
        
        /// <remarks/>
        public decimal Available_Rating {
            get {
                return this.available_RatingField;
            }
            set {
                this.available_RatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Available_RatingSpecified {
            get {
                return this.available_RatingFieldSpecified;
            }
            set {
                this.available_RatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Supervisor_Rating {
            get {
                return this.supervisor_RatingField;
            }
            set {
                this.supervisor_RatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Supervisor_RatingSpecified {
            get {
                return this.supervisor_RatingFieldSpecified;
            }
            set {
                this.supervisor_RatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Employee_Rating {
            get {
                return this.employee_RatingField;
            }
            set {
                this.employee_RatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Employee_RatingSpecified {
            get {
                return this.employee_RatingFieldSpecified;
            }
            set {
                this.employee_RatingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public partial class ConfirmationCard_Filter {
        
        private ConfirmationCard_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public ConfirmationCard_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public enum ConfirmationCard_Fields {
        
        /// <remarks/>
        Application_No,
        
        /// <remarks/>
        Employee_No,
        
        /// <remarks/>
        Employee_Name,
        
        /// <remarks/>
        Date_of_Employment,
        
        /// <remarks/>
        Department,
        
        /// <remarks/>
        Supervisor,
        
        /// <remarks/>
        Second_Line_Supervisor,
        
        /// <remarks/>
        Level,
        
        /// <remarks/>
        Appraisal_Type,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Date_of_Review,
        
        /// <remarks/>
        Start_Date,
        
        /// <remarks/>
        End_Date,
        
        /// <remarks/>
        Score,
        
        /// <remarks/>
        KPI_Score,
        
        /// <remarks/>
        User_ID,
        
        /// <remarks/>
        Comment,
        
        /// <remarks/>
        Second_Line_Supervisor_Comment,
        
        /// <remarks/>
        Development_Areas,
        
        /// <remarks/>
        Training_Ideas,
        
        /// <remarks/>
        Employee_Comment,
        
        /// <remarks/>
        Responsibility_Center,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public partial class HR_Confirmation_KPI_D {
        
        private string keyField;
        
        private string objectivesField;
        
        private string document_NoField;
        
        private decimal weightField;
        
        private bool weightFieldSpecified;
        
        private string behavioural_GroupField;
        
        private string ratingsField;
        
        private decimal scoreField;
        
        private bool scoreFieldSpecified;
        
        private decimal kPI_WeightingField;
        
        private bool kPI_WeightingFieldSpecified;
        
        private decimal target_Score_PercentField;
        
        private bool target_Score_PercentFieldSpecified;
        
        private string employee_NoField;
        
        private int line_NoField;
        
        private bool line_NoFieldSpecified;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Objectives {
            get {
                return this.objectivesField;
            }
            set {
                this.objectivesField = value;
            }
        }
        
        /// <remarks/>
        public string Document_No {
            get {
                return this.document_NoField;
            }
            set {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Behavioural_Group {
            get {
                return this.behavioural_GroupField;
            }
            set {
                this.behavioural_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Ratings {
            get {
                return this.ratingsField;
            }
            set {
                this.ratingsField = value;
            }
        }
        
        /// <remarks/>
        public decimal Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal KPI_Weighting {
            get {
                return this.kPI_WeightingField;
            }
            set {
                this.kPI_WeightingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KPI_WeightingSpecified {
            get {
                return this.kPI_WeightingFieldSpecified;
            }
            set {
                this.kPI_WeightingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Target_Score_Percent {
            get {
                return this.target_Score_PercentField;
            }
            set {
                this.target_Score_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Target_Score_PercentSpecified {
            get {
                return this.target_Score_PercentFieldSpecified;
            }
            set {
                this.target_Score_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Employee_No {
            get {
                return this.employee_NoField;
            }
            set {
                this.employee_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Line_No {
            get {
                return this.line_NoField;
            }
            set {
                this.line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_NoSpecified {
            get {
                return this.line_NoFieldSpecified;
            }
            set {
                this.line_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public partial class HR_Confirmation_KPI_C {
        
        private string keyField;
        
        private string objectivesField;
        
        private decimal weightField;
        
        private bool weightFieldSpecified;
        
        private string behavioural_GroupField;
        
        private string ratingsField;
        
        private decimal scoreField;
        
        private bool scoreFieldSpecified;
        
        private decimal kPI_WeightingField;
        
        private bool kPI_WeightingFieldSpecified;
        
        private string document_NoField;
        
        private decimal target_Score_PercentField;
        
        private bool target_Score_PercentFieldSpecified;
        
        private string employee_NoField;
        
        private int line_NoField;
        
        private bool line_NoFieldSpecified;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Objectives {
            get {
                return this.objectivesField;
            }
            set {
                this.objectivesField = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Behavioural_Group {
            get {
                return this.behavioural_GroupField;
            }
            set {
                this.behavioural_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Ratings {
            get {
                return this.ratingsField;
            }
            set {
                this.ratingsField = value;
            }
        }
        
        /// <remarks/>
        public decimal Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal KPI_Weighting {
            get {
                return this.kPI_WeightingField;
            }
            set {
                this.kPI_WeightingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KPI_WeightingSpecified {
            get {
                return this.kPI_WeightingFieldSpecified;
            }
            set {
                this.kPI_WeightingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Document_No {
            get {
                return this.document_NoField;
            }
            set {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Target_Score_Percent {
            get {
                return this.target_Score_PercentField;
            }
            set {
                this.target_Score_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Target_Score_PercentSpecified {
            get {
                return this.target_Score_PercentFieldSpecified;
            }
            set {
                this.target_Score_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Employee_No {
            get {
                return this.employee_NoField;
            }
            set {
                this.employee_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Line_No {
            get {
                return this.line_NoField;
            }
            set {
                this.line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_NoSpecified {
            get {
                return this.line_NoFieldSpecified;
            }
            set {
                this.line_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public partial class HR_KPI_Confirmation_B {
        
        private string keyField;
        
        private string objectivesField;
        
        private decimal weightField;
        
        private bool weightFieldSpecified;
        
        private string behavioural_GroupField;
        
        private string ratingsField;
        
        private decimal scoreField;
        
        private bool scoreFieldSpecified;
        
        private decimal kPI_WeightingField;
        
        private bool kPI_WeightingFieldSpecified;
        
        private string document_NoField;
        
        private decimal target_Score_PercentField;
        
        private bool target_Score_PercentFieldSpecified;
        
        private string employee_NoField;
        
        private int line_NoField;
        
        private bool line_NoFieldSpecified;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Objectives {
            get {
                return this.objectivesField;
            }
            set {
                this.objectivesField = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Behavioural_Group {
            get {
                return this.behavioural_GroupField;
            }
            set {
                this.behavioural_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Ratings {
            get {
                return this.ratingsField;
            }
            set {
                this.ratingsField = value;
            }
        }
        
        /// <remarks/>
        public decimal Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal KPI_Weighting {
            get {
                return this.kPI_WeightingField;
            }
            set {
                this.kPI_WeightingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KPI_WeightingSpecified {
            get {
                return this.kPI_WeightingFieldSpecified;
            }
            set {
                this.kPI_WeightingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Document_No {
            get {
                return this.document_NoField;
            }
            set {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Target_Score_Percent {
            get {
                return this.target_Score_PercentField;
            }
            set {
                this.target_Score_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Target_Score_PercentSpecified {
            get {
                return this.target_Score_PercentFieldSpecified;
            }
            set {
                this.target_Score_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Employee_No {
            get {
                return this.employee_NoField;
            }
            set {
                this.employee_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Line_No {
            get {
                return this.line_NoField;
            }
            set {
                this.line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_NoSpecified {
            get {
                return this.line_NoFieldSpecified;
            }
            set {
                this.line_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/confirmationcard")]
    public partial class HR_Confirmation_KPI_A {
        
        private string keyField;
        
        private string objectivesField;
        
        private decimal weightField;
        
        private bool weightFieldSpecified;
        
        private string behavioural_GroupField;
        
        private string ratingsField;
        
        private decimal scoreField;
        
        private bool scoreFieldSpecified;
        
        private decimal kPI_WeightingField;
        
        private bool kPI_WeightingFieldSpecified;
        
        private string document_NoField;
        
        private decimal target_Score_PercentField;
        
        private bool target_Score_PercentFieldSpecified;
        
        private string employee_NoField;
        
        private int line_NoField;
        
        private bool line_NoFieldSpecified;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Objectives {
            get {
                return this.objectivesField;
            }
            set {
                this.objectivesField = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Behavioural_Group {
            get {
                return this.behavioural_GroupField;
            }
            set {
                this.behavioural_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Ratings {
            get {
                return this.ratingsField;
            }
            set {
                this.ratingsField = value;
            }
        }
        
        /// <remarks/>
        public decimal Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal KPI_Weighting {
            get {
                return this.kPI_WeightingField;
            }
            set {
                this.kPI_WeightingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KPI_WeightingSpecified {
            get {
                return this.kPI_WeightingFieldSpecified;
            }
            set {
                this.kPI_WeightingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Document_No {
            get {
                return this.document_NoField;
            }
            set {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Target_Score_Percent {
            get {
                return this.target_Score_PercentField;
            }
            set {
                this.target_Score_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Target_Score_PercentSpecified {
            get {
                return this.target_Score_PercentFieldSpecified;
            }
            set {
                this.target_Score_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Employee_No {
            get {
                return this.employee_NoField;
            }
            set {
                this.employee_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Line_No {
            get {
                return this.line_NoField;
            }
            set {
                this.line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_NoSpecified {
            get {
                return this.line_NoFieldSpecified;
            }
            set {
                this.line_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConfirmationCard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmationCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConfirmationCard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmationCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConfirmationCard[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmationCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConfirmationCard ConfirmationCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmationCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConfirmationCard[] ConfirmationCard_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmationCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConfirmationCard ConfirmationCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmationCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConfirmationCard[] ConfirmationCard_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmationCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Delete_HR_Confirmation_KPI_ACompletedEventHandler(object sender, Delete_HR_Confirmation_KPI_ACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_HR_Confirmation_KPI_ACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_HR_Confirmation_KPI_ACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Delete_HR_KPI_Confirmation_BCompletedEventHandler(object sender, Delete_HR_KPI_Confirmation_BCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_HR_KPI_Confirmation_BCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_HR_KPI_Confirmation_BCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Delete_HR_Confirmation_KPI_CCompletedEventHandler(object sender, Delete_HR_Confirmation_KPI_CCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_HR_Confirmation_KPI_CCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_HR_Confirmation_KPI_CCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Delete_HR_Confirmation_KPI_DCompletedEventHandler(object sender, Delete_HR_Confirmation_KPI_DCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_HR_Confirmation_KPI_DCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_HR_Confirmation_KPI_DCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591