//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NAV_HR_WINDOW.HRSetup_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HRSetup_Binding", Namespace="urn:microsoft-dynamics-schemas/page/hrsetup")]
    public partial class HRSetup_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HRSetup_Service() {
            this.Url = global::NAV_HR_WINDOW.Properties.Settings.Default.NAV_HR_WINDOW_HRSetup_Service_HRSetup_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/hrsetup:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("HRSetup")]
        public HRSetup ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((HRSetup)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/hrsetup:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HRSetup[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] HRSetup_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((HRSetup[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(HRSetup_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(HRSetup_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/hrsetup:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/hrsetup:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/hrsetup:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref HRSetup HRSetup) {
            object[] results = this.Invoke("Update", new object[] {
                        HRSetup});
            HRSetup = ((HRSetup)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(HRSetup HRSetup) {
            this.UpdateAsync(HRSetup, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(HRSetup HRSetup, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        HRSetup}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/hrsetup:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/hrsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref HRSetup[] HRSetup_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        HRSetup_List});
            HRSetup_List = ((HRSetup[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(HRSetup[] HRSetup_List) {
            this.UpdateMultipleAsync(HRSetup_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(HRSetup[] HRSetup_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        HRSetup_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/hrsetup")]
    public partial class HRSetup {
        
        private string keyField;
        
        private string appraisal_PeriodField;
        
        private bool open_PeriodField;
        
        private bool open_PeriodFieldSpecified;
        
        private string base_CalendarField;
        
        private decimal meal_AmountField;
        
        private bool meal_AmountFieldSpecified;
        
        private string companys_Group_EmailField;
        
        private string shared_Document_PathField;
        
        private string confirmation_NosField;
        
        private decimal loan_Amount_PercentField;
        
        private bool loan_Amount_PercentFieldSpecified;
        
        private System.DateTime leave_Posting_PeriodFROMField;
        
        private bool leave_Posting_PeriodFROMFieldSpecified;
        
        private System.DateTime leave_Posting_PeriodTOField;
        
        private bool leave_Posting_PeriodTOFieldSpecified;
        
        private string default_Leave_Posting_TemplateField;
        
        private string default_Leave_Posting_BatchField;
        
        private string annual_Leave_QualificationField;
        
        private int leave_Allowance_DaysField;
        
        private bool leave_Allowance_DaysFieldSpecified;
        
        private string maternity_Leave_PeriodField;
        
        private System.DateTime forfeit_Leave_AfterField;
        
        private bool forfeit_Leave_AfterFieldSpecified;
        
        private string current_Leave_PeriodField;
        
        private int maternity_Application_BeforeField;
        
        private bool maternity_Application_BeforeFieldSpecified;
        
        private int leave_Application_BeforeField;
        
        private bool leave_Application_BeforeFieldSpecified;
        
        private int training_Application_BeforeField;
        
        private bool training_Application_BeforeFieldSpecified;
        
        private string employee_NosField;
        
        private string training_Application_NosField;
        
        private string leave_Application_NosField;
        
        private string disciplinary_Cases_NosField;
        
        private string transport_Req_NosField;
        
        private string employee_Requisition_NosField;
        
        private string job_Application_NosField;
        
        private string exit_Interview_NosField;
        
        private string appraisal_NosField;
        
        private string company_ActivitiesField;
        
        private string job_Interview_NosField;
        
        private string ticket_NosField;
        
        private string loan_NosField;
        
        private string career_EventField;
        
        private string training_Need_NosField;
        
        private string leave_Acknowledgement_NosField;
        
        private string employee_ID_NosField;
        
        private string transaction_NosField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Appraisal_Period {
            get {
                return this.appraisal_PeriodField;
            }
            set {
                this.appraisal_PeriodField = value;
            }
        }
        
        /// <remarks/>
        public bool Open_Period {
            get {
                return this.open_PeriodField;
            }
            set {
                this.open_PeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Open_PeriodSpecified {
            get {
                return this.open_PeriodFieldSpecified;
            }
            set {
                this.open_PeriodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Base_Calendar {
            get {
                return this.base_CalendarField;
            }
            set {
                this.base_CalendarField = value;
            }
        }
        
        /// <remarks/>
        public decimal Meal_Amount {
            get {
                return this.meal_AmountField;
            }
            set {
                this.meal_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Meal_AmountSpecified {
            get {
                return this.meal_AmountFieldSpecified;
            }
            set {
                this.meal_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Company\'s_Group_Email")]
        public string Companys_Group_Email {
            get {
                return this.companys_Group_EmailField;
            }
            set {
                this.companys_Group_EmailField = value;
            }
        }
        
        /// <remarks/>
        public string Shared_Document_Path {
            get {
                return this.shared_Document_PathField;
            }
            set {
                this.shared_Document_PathField = value;
            }
        }
        
        /// <remarks/>
        public string Confirmation_Nos {
            get {
                return this.confirmation_NosField;
            }
            set {
                this.confirmation_NosField = value;
            }
        }
        
        /// <remarks/>
        public decimal Loan_Amount_Percent {
            get {
                return this.loan_Amount_PercentField;
            }
            set {
                this.loan_Amount_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Loan_Amount_PercentSpecified {
            get {
                return this.loan_Amount_PercentFieldSpecified;
            }
            set {
                this.loan_Amount_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Leave_Posting_Period[FROM]", DataType="date")]
        public System.DateTime Leave_Posting_PeriodFROM {
            get {
                return this.leave_Posting_PeriodFROMField;
            }
            set {
                this.leave_Posting_PeriodFROMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_Posting_PeriodFROMSpecified {
            get {
                return this.leave_Posting_PeriodFROMFieldSpecified;
            }
            set {
                this.leave_Posting_PeriodFROMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Leave_Posting_Period[TO]", DataType="date")]
        public System.DateTime Leave_Posting_PeriodTO {
            get {
                return this.leave_Posting_PeriodTOField;
            }
            set {
                this.leave_Posting_PeriodTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_Posting_PeriodTOSpecified {
            get {
                return this.leave_Posting_PeriodTOFieldSpecified;
            }
            set {
                this.leave_Posting_PeriodTOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Default_Leave_Posting_Template {
            get {
                return this.default_Leave_Posting_TemplateField;
            }
            set {
                this.default_Leave_Posting_TemplateField = value;
            }
        }
        
        /// <remarks/>
        public string Default_Leave_Posting_Batch {
            get {
                return this.default_Leave_Posting_BatchField;
            }
            set {
                this.default_Leave_Posting_BatchField = value;
            }
        }
        
        /// <remarks/>
        public string Annual_Leave_Qualification {
            get {
                return this.annual_Leave_QualificationField;
            }
            set {
                this.annual_Leave_QualificationField = value;
            }
        }
        
        /// <remarks/>
        public int Leave_Allowance_Days {
            get {
                return this.leave_Allowance_DaysField;
            }
            set {
                this.leave_Allowance_DaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_Allowance_DaysSpecified {
            get {
                return this.leave_Allowance_DaysFieldSpecified;
            }
            set {
                this.leave_Allowance_DaysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Maternity_Leave_Period {
            get {
                return this.maternity_Leave_PeriodField;
            }
            set {
                this.maternity_Leave_PeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Forfeit_Leave_After {
            get {
                return this.forfeit_Leave_AfterField;
            }
            set {
                this.forfeit_Leave_AfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Forfeit_Leave_AfterSpecified {
            get {
                return this.forfeit_Leave_AfterFieldSpecified;
            }
            set {
                this.forfeit_Leave_AfterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Current_Leave_Period {
            get {
                return this.current_Leave_PeriodField;
            }
            set {
                this.current_Leave_PeriodField = value;
            }
        }
        
        /// <remarks/>
        public int Maternity_Application_Before {
            get {
                return this.maternity_Application_BeforeField;
            }
            set {
                this.maternity_Application_BeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Maternity_Application_BeforeSpecified {
            get {
                return this.maternity_Application_BeforeFieldSpecified;
            }
            set {
                this.maternity_Application_BeforeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Leave_Application_Before {
            get {
                return this.leave_Application_BeforeField;
            }
            set {
                this.leave_Application_BeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_Application_BeforeSpecified {
            get {
                return this.leave_Application_BeforeFieldSpecified;
            }
            set {
                this.leave_Application_BeforeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Training_Application_Before {
            get {
                return this.training_Application_BeforeField;
            }
            set {
                this.training_Application_BeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Training_Application_BeforeSpecified {
            get {
                return this.training_Application_BeforeFieldSpecified;
            }
            set {
                this.training_Application_BeforeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Employee_Nos {
            get {
                return this.employee_NosField;
            }
            set {
                this.employee_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Training_Application_Nos {
            get {
                return this.training_Application_NosField;
            }
            set {
                this.training_Application_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Leave_Application_Nos {
            get {
                return this.leave_Application_NosField;
            }
            set {
                this.leave_Application_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Disciplinary_Cases_Nos {
            get {
                return this.disciplinary_Cases_NosField;
            }
            set {
                this.disciplinary_Cases_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Transport_Req_Nos {
            get {
                return this.transport_Req_NosField;
            }
            set {
                this.transport_Req_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Employee_Requisition_Nos {
            get {
                return this.employee_Requisition_NosField;
            }
            set {
                this.employee_Requisition_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Job_Application_Nos {
            get {
                return this.job_Application_NosField;
            }
            set {
                this.job_Application_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Exit_Interview_Nos {
            get {
                return this.exit_Interview_NosField;
            }
            set {
                this.exit_Interview_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Appraisal_Nos {
            get {
                return this.appraisal_NosField;
            }
            set {
                this.appraisal_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Company_Activities {
            get {
                return this.company_ActivitiesField;
            }
            set {
                this.company_ActivitiesField = value;
            }
        }
        
        /// <remarks/>
        public string Job_Interview_Nos {
            get {
                return this.job_Interview_NosField;
            }
            set {
                this.job_Interview_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Ticket_Nos {
            get {
                return this.ticket_NosField;
            }
            set {
                this.ticket_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Loan_Nos {
            get {
                return this.loan_NosField;
            }
            set {
                this.loan_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Career_Event {
            get {
                return this.career_EventField;
            }
            set {
                this.career_EventField = value;
            }
        }
        
        /// <remarks/>
        public string Training_Need_Nos {
            get {
                return this.training_Need_NosField;
            }
            set {
                this.training_Need_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Leave_Acknowledgement_Nos {
            get {
                return this.leave_Acknowledgement_NosField;
            }
            set {
                this.leave_Acknowledgement_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Employee_ID_Nos {
            get {
                return this.employee_ID_NosField;
            }
            set {
                this.employee_ID_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Transaction_Nos {
            get {
                return this.transaction_NosField;
            }
            set {
                this.transaction_NosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/hrsetup")]
    public partial class HRSetup_Filter {
        
        private HRSetup_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public HRSetup_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/hrsetup")]
    public enum HRSetup_Fields {
        
        /// <remarks/>
        Appraisal_Period,
        
        /// <remarks/>
        Open_Period,
        
        /// <remarks/>
        Base_Calendar,
        
        /// <remarks/>
        Meal_Amount,
        
        /// <remarks/>
        Company_x0027_s_Group_Email,
        
        /// <remarks/>
        Shared_Document_Path,
        
        /// <remarks/>
        Confirmation_Nos,
        
        /// <remarks/>
        Loan_Amount_Percent,
        
        /// <remarks/>
        Leave_Posting_Period_x005B_FROM_x005D_,
        
        /// <remarks/>
        Leave_Posting_Period_x005B_TO_x005D_,
        
        /// <remarks/>
        Default_Leave_Posting_Template,
        
        /// <remarks/>
        Default_Leave_Posting_Batch,
        
        /// <remarks/>
        Annual_Leave_Qualification,
        
        /// <remarks/>
        Leave_Allowance_Days,
        
        /// <remarks/>
        Maternity_Leave_Period,
        
        /// <remarks/>
        Forfeit_Leave_After,
        
        /// <remarks/>
        Current_Leave_Period,
        
        /// <remarks/>
        Maternity_Application_Before,
        
        /// <remarks/>
        Leave_Application_Before,
        
        /// <remarks/>
        Training_Application_Before,
        
        /// <remarks/>
        Employee_Nos,
        
        /// <remarks/>
        Training_Application_Nos,
        
        /// <remarks/>
        Leave_Application_Nos,
        
        /// <remarks/>
        Disciplinary_Cases_Nos,
        
        /// <remarks/>
        Transport_Req_Nos,
        
        /// <remarks/>
        Employee_Requisition_Nos,
        
        /// <remarks/>
        Job_Application_Nos,
        
        /// <remarks/>
        Exit_Interview_Nos,
        
        /// <remarks/>
        Appraisal_Nos,
        
        /// <remarks/>
        Company_Activities,
        
        /// <remarks/>
        Job_Interview_Nos,
        
        /// <remarks/>
        Ticket_Nos,
        
        /// <remarks/>
        Loan_Nos,
        
        /// <remarks/>
        Career_Event,
        
        /// <remarks/>
        Training_Need_Nos,
        
        /// <remarks/>
        Leave_Acknowledgement_Nos,
        
        /// <remarks/>
        Employee_ID_Nos,
        
        /// <remarks/>
        Transaction_Nos,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HRSetup Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HRSetup)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HRSetup[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HRSetup[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HRSetup HRSetup {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HRSetup)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HRSetup[] HRSetup_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HRSetup[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591