//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NAV_HR_WINDOW.ApprovalEntry {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ApprovalEntry_Binding", Namespace="urn:microsoft-dynamics-schemas/page/approvalentry")]
    public partial class ApprovalEntry_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ApprovalEntry_Service() {
            this.Url = global::NAV_HR_WINDOW.Properties.Settings.Default.NAV_HR_WINDOW_ApprovalEntry_ApprovalEntry_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/approvalentry:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ApprovalEntry")]
        public ApprovalEntry Read(int Table_ID, string Document_Type, string Document_No, int Sequence_No) {
            object[] results = this.Invoke("Read", new object[] {
                        Table_ID,
                        Document_Type,
                        Document_No,
                        Sequence_No});
            return ((ApprovalEntry)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(int Table_ID, string Document_Type, string Document_No, int Sequence_No) {
            this.ReadAsync(Table_ID, Document_Type, Document_No, Sequence_No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(int Table_ID, string Document_Type, string Document_No, int Sequence_No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Table_ID,
                        Document_Type,
                        Document_No,
                        Sequence_No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/approvalentry:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ApprovalEntry")]
        public ApprovalEntry ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((ApprovalEntry)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/approvalentry:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ApprovalEntry[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] ApprovalEntry_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((ApprovalEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ApprovalEntry_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ApprovalEntry_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/approvalentry:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/approvalentry:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/approvalentry:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref ApprovalEntry ApprovalEntry) {
            object[] results = this.Invoke("Create", new object[] {
                        ApprovalEntry});
            ApprovalEntry = ((ApprovalEntry)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(ApprovalEntry ApprovalEntry) {
            this.CreateAsync(ApprovalEntry, null);
        }
        
        /// <remarks/>
        public void CreateAsync(ApprovalEntry ApprovalEntry, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        ApprovalEntry}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/approvalentry:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ApprovalEntry[] ApprovalEntry_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        ApprovalEntry_List});
            ApprovalEntry_List = ((ApprovalEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(ApprovalEntry[] ApprovalEntry_List) {
            this.CreateMultipleAsync(ApprovalEntry_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(ApprovalEntry[] ApprovalEntry_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        ApprovalEntry_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/approvalentry:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref ApprovalEntry ApprovalEntry) {
            object[] results = this.Invoke("Update", new object[] {
                        ApprovalEntry});
            ApprovalEntry = ((ApprovalEntry)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(ApprovalEntry ApprovalEntry) {
            this.UpdateAsync(ApprovalEntry, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(ApprovalEntry ApprovalEntry, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        ApprovalEntry}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/approvalentry:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ApprovalEntry[] ApprovalEntry_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        ApprovalEntry_List});
            ApprovalEntry_List = ((ApprovalEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(ApprovalEntry[] ApprovalEntry_List) {
            this.UpdateMultipleAsync(ApprovalEntry_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(ApprovalEntry[] ApprovalEntry_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        ApprovalEntry_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/approvalentry:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/approvalentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/approvalentry")]
    public partial class ApprovalEntry {
        
        private string keyField;
        
        private Document_Type document_TypeField;
        
        private bool document_TypeFieldSpecified;
        
        private Approval_Type approval_TypeField;
        
        private bool approval_TypeFieldSpecified;
        
        private string document_NoField;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string sender_IDField;
        
        private string sender_BUField;
        
        private Stage stageField;
        
        private bool stageFieldSpecified;
        
        private string approver_IDField;
        
        private string last_Modified_By_IDField;
        
        private System.DateTime last_Date_Time_ModifiedField;
        
        private bool last_Date_Time_ModifiedFieldSpecified;
        
        private System.DateTime date_Time_Sent_for_ApprovalField;
        
        private bool date_Time_Sent_for_ApprovalFieldSpecified;
        
        private decimal amount_LCYField;
        
        private bool amount_LCYFieldSpecified;
        
        private string approval_CodeField;
        
        private int sequence_NoField;
        
        private bool sequence_NoFieldSpecified;
        
        private int table_IDField;
        
        private bool table_IDFieldSpecified;
        
        private Limit_Type limit_TypeField;
        
        private bool limit_TypeFieldSpecified;
        
        private string salespers_Purch_CodeField;
        
        private string currency_CodeField;
        
        private decimal available_Credit_Limit_LCYField;
        
        private bool available_Credit_Limit_LCYFieldSpecified;
        
        private bool commentField;
        
        private bool commentFieldSpecified;
        
        private System.DateTime due_DateField;
        
        private bool due_DateFieldSpecified;
        
        private decimal discount_PercentField;
        
        private bool discount_PercentFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public Document_Type Document_Type {
            get {
                return this.document_TypeField;
            }
            set {
                this.document_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_TypeSpecified {
            get {
                return this.document_TypeFieldSpecified;
            }
            set {
                this.document_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Approval_Type Approval_Type {
            get {
                return this.approval_TypeField;
            }
            set {
                this.approval_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Approval_TypeSpecified {
            get {
                return this.approval_TypeFieldSpecified;
            }
            set {
                this.approval_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Document_No {
            get {
                return this.document_NoField;
            }
            set {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Sender_ID {
            get {
                return this.sender_IDField;
            }
            set {
                this.sender_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Sender_BU {
            get {
                return this.sender_BUField;
            }
            set {
                this.sender_BUField = value;
            }
        }
        
        /// <remarks/>
        public Stage Stage {
            get {
                return this.stageField;
            }
            set {
                this.stageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StageSpecified {
            get {
                return this.stageFieldSpecified;
            }
            set {
                this.stageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Approver_ID {
            get {
                return this.approver_IDField;
            }
            set {
                this.approver_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Last_Modified_By_ID {
            get {
                return this.last_Modified_By_IDField;
            }
            set {
                this.last_Modified_By_IDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Last_Date_Time_Modified {
            get {
                return this.last_Date_Time_ModifiedField;
            }
            set {
                this.last_Date_Time_ModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_Time_ModifiedSpecified {
            get {
                return this.last_Date_Time_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_Time_ModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date_Time_Sent_for_Approval {
            get {
                return this.date_Time_Sent_for_ApprovalField;
            }
            set {
                this.date_Time_Sent_for_ApprovalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_Time_Sent_for_ApprovalSpecified {
            get {
                return this.date_Time_Sent_for_ApprovalFieldSpecified;
            }
            set {
                this.date_Time_Sent_for_ApprovalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount_LCY {
            get {
                return this.amount_LCYField;
            }
            set {
                this.amount_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Amount_LCYSpecified {
            get {
                return this.amount_LCYFieldSpecified;
            }
            set {
                this.amount_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Approval_Code {
            get {
                return this.approval_CodeField;
            }
            set {
                this.approval_CodeField = value;
            }
        }
        
        /// <remarks/>
        public int Sequence_No {
            get {
                return this.sequence_NoField;
            }
            set {
                this.sequence_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Sequence_NoSpecified {
            get {
                return this.sequence_NoFieldSpecified;
            }
            set {
                this.sequence_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Table_ID {
            get {
                return this.table_IDField;
            }
            set {
                this.table_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Table_IDSpecified {
            get {
                return this.table_IDFieldSpecified;
            }
            set {
                this.table_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Limit_Type Limit_Type {
            get {
                return this.limit_TypeField;
            }
            set {
                this.limit_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Limit_TypeSpecified {
            get {
                return this.limit_TypeFieldSpecified;
            }
            set {
                this.limit_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Salespers_Purch_Code {
            get {
                return this.salespers_Purch_CodeField;
            }
            set {
                this.salespers_Purch_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Currency_Code {
            get {
                return this.currency_CodeField;
            }
            set {
                this.currency_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Available_Credit_Limit_LCY {
            get {
                return this.available_Credit_Limit_LCYField;
            }
            set {
                this.available_Credit_Limit_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Available_Credit_Limit_LCYSpecified {
            get {
                return this.available_Credit_Limit_LCYFieldSpecified;
            }
            set {
                this.available_Credit_Limit_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommentSpecified {
            get {
                return this.commentFieldSpecified;
            }
            set {
                this.commentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Due_Date {
            get {
                return this.due_DateField;
            }
            set {
                this.due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Due_DateSpecified {
            get {
                return this.due_DateFieldSpecified;
            }
            set {
                this.due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Discount_Percent {
            get {
                return this.discount_PercentField;
            }
            set {
                this.discount_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Discount_PercentSpecified {
            get {
                return this.discount_PercentFieldSpecified;
            }
            set {
                this.discount_PercentFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/approvalentry")]
    public enum Document_Type {
        
        /// <remarks/>
        Quote,
        
        /// <remarks/>
        Order,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        Credit_Memo,
        
        /// <remarks/>
        Blanket_Order,
        
        /// <remarks/>
        Return_Order,
        
        /// <remarks/>
        JV,
        
        /// <remarks/>
        Payment_Voucher,
        
        /// <remarks/>
        Petty_Cash,
        
        /// <remarks/>
        Requisition,
        
        /// <remarks/>
        InterBank,
        
        /// <remarks/>
        Staff_Claim,
        
        /// <remarks/>
        Staff_Advance,
        
        /// <remarks/>
        AdvanceSurrender,
        
        /// <remarks/>
        Capex,
        
        /// <remarks/>
        IJ,
        
        /// <remarks/>
        Hr_Job,
        
        /// <remarks/>
        Emp_Loan,
        
        /// <remarks/>
        Leave_Application,
        
        /// <remarks/>
        Employee_Requisition,
        
        /// <remarks/>
        Interview_Evaluation,
        
        /// <remarks/>
        Training_Requisition,
        
        /// <remarks/>
        Appraisal,
        
        /// <remarks/>
        HMO,
        
        /// <remarks/>
        Canteen,
        
        /// <remarks/>
        EmpTransaction,
        
        /// <remarks/>
        LeaveAck,
        
        /// <remarks/>
        PFAMod,
        
        /// <remarks/>
        PFATransfer,
        
        /// <remarks/>
        Confirmation,
        
        /// <remarks/>
        Employee,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/approvalentry")]
    public enum Approval_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Sales_Pers_Purchaser,
        
        /// <remarks/>
        Approver,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/approvalentry")]
    public enum Status {
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Canceled,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Approved,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/approvalentry")]
    public enum Stage {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        HOD,
        
        /// <remarks/>
        Audit,
        
        /// <remarks/>
        MGT,
        
        /// <remarks/>
        Executive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/approvalentry")]
    public enum Limit_Type {
        
        /// <remarks/>
        Approval_Limits,
        
        /// <remarks/>
        Credit_Limits,
        
        /// <remarks/>
        Request_Limits,
        
        /// <remarks/>
        No_Limits,
        
        /// <remarks/>
        Tiered,
        
        /// <remarks/>
        Discount_Limits,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/approvalentry")]
    public partial class ApprovalEntry_Filter {
        
        private ApprovalEntry_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public ApprovalEntry_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/approvalentry")]
    public enum ApprovalEntry_Fields {
        
        /// <remarks/>
        Document_Type,
        
        /// <remarks/>
        Approval_Type,
        
        /// <remarks/>
        Document_No,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Sender_ID,
        
        /// <remarks/>
        Sender_BU,
        
        /// <remarks/>
        Stage,
        
        /// <remarks/>
        Approver_ID,
        
        /// <remarks/>
        Last_Modified_By_ID,
        
        /// <remarks/>
        Last_Date_Time_Modified,
        
        /// <remarks/>
        Date_Time_Sent_for_Approval,
        
        /// <remarks/>
        Amount_LCY,
        
        /// <remarks/>
        Approval_Code,
        
        /// <remarks/>
        Sequence_No,
        
        /// <remarks/>
        Table_ID,
        
        /// <remarks/>
        Limit_Type,
        
        /// <remarks/>
        Salespers_Purch_Code,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        Available_Credit_Limit_LCY,
        
        /// <remarks/>
        Comment,
        
        /// <remarks/>
        Due_Date,
        
        /// <remarks/>
        Discount_Percent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApprovalEntry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApprovalEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApprovalEntry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApprovalEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApprovalEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApprovalEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApprovalEntry ApprovalEntry {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApprovalEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApprovalEntry[] ApprovalEntry_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApprovalEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApprovalEntry ApprovalEntry {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApprovalEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApprovalEntry[] ApprovalEntry_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApprovalEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591